# Generated by Django 2.2.5 on 2019-10-23 02:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('cust_id', models.AutoField(primary_key=True, serialize=False)),
                ('cust_name', models.CharField(max_length=50)),
                ('cust_address', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('order_id', models.AutoField(primary_key=True, serialize=False)),
                ('order_date', models.DateTimeField(auto_now=True)),
                ('state', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('prod_id', models.AutoField(primary_key=True, serialize=False)),
                ('prod_name', models.CharField(max_length=50)),
                ('prod_desc', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='RepoMessage',
            fields=[
                ('repo_mess_id', models.AutoField(primary_key=True, serialize=False)),
                ('repo_mess_info', models.TextField(null=True)),
                ('quantity', models.IntegerField()),
                ('direction', models.CharField(max_length=50)),
                ('repo_mess_datetime', models.DateTimeField(auto_now=True)),
                ('state', models.CharField(default='未完成', max_length=50)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dbc2019.Order')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dbc2019.Product')),
            ],
        ),
        migrations.CreateModel(
            name='Repository',
            fields=[
                ('repo_id', models.AutoField(primary_key=True, serialize=False)),
                ('place', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=50, null=True)),
                ('repo_capacity', models.IntegerField()),
                ('repo_occupy', models.IntegerField(default=0)),
                ('admin', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TransMessage',
            fields=[
                ('trans_mess_id', models.AutoField(primary_key=True, serialize=False)),
                ('trans_mess_info', models.TextField(null=True)),
                ('quantity', models.IntegerField()),
                ('trans_mess_datetime', models.DateTimeField(auto_now=True)),
                ('state', models.CharField(default='未完成', max_length=50)),
                ('flag', models.IntegerField(default=0)),
                ('from_repository', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='from_mess', to='dbc2019.Repository')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dbc2019.Product')),
                ('to_repository', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='to_mess', to='dbc2019.Repository')),
            ],
        ),
        migrations.CreateModel(
            name='WorkMessage',
            fields=[
                ('work_mess_id', models.AutoField(primary_key=True, serialize=False)),
                ('work_mess_info', models.TextField(null=True)),
                ('quantity', models.IntegerField()),
                ('direction', models.CharField(max_length=50)),
                ('work_mess_datetime', models.DateTimeField(auto_now=True)),
                ('admin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dbc2019.Product')),
                ('repo_message', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='dbc2019.RepoMessage')),
                ('trans_message', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dbc2019.TransMessage')),
            ],
        ),
        migrations.CreateModel(
            name='RepositoryItem',
            fields=[
                ('repo_item_id', models.AutoField(primary_key=True, serialize=False)),
                ('quantity', models.IntegerField()),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='dbc2019.Product')),
                ('repository', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dbc2019.Repository')),
            ],
        ),
        migrations.AddField(
            model_name='repomessage',
            name='repository',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dbc2019.Repository'),
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('order_item_id', models.AutoField(primary_key=True, serialize=False)),
                ('quantity', models.IntegerField()),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dbc2019.Order')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dbc2019.Product')),
            ],
        ),
    ]
