# Generated by Django 2.2.5 on 2019-12-13 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dbc2019', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='repository',
            name='repo_place',
            field=models.CharField(max_length=100),
        ),
    ]
