# Generated by Django 2.2.5 on 2019-11-30 20:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dbc2019', '0002_auto_20191201_0406'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dbc2019.Customer'),
        ),
    ]
