# Generated by Django 2.2.5 on 2019-12-13 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dbc2019', '0002_auto_20191213_2255'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='repomessage',
            name='repo_mess_datetime',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='transmessage',
            name='trans_mess_datetime',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='workmessage',
            name='work_mess_datetime',
            field=models.DateTimeField(),
        ),
    ]
